"""
Space AI 2.0

Base Decision Strategy

Abstract base class implemented by every Decision Strategy.

Concrete strategies transform a DecisionContext into an
immutable Decision.

This class defines the common contract shared by every
Decision Strategy implementation.

Compatible with:
    - Python 3.13.5
    - Ruff
    - MyPy (strict)
"""

from __future__ import annotations

# ============================================================================
# Standard Library
# ============================================================================
from abc import ABC, abstractmethod

# ============================================================================
# Space AI - Same Package
# ============================================================================
from ..decision import Decision
from ..decision_context import DecisionContext


class BaseDecisionStrategy(ABC):
    """
    Abstract base class for every Decision Strategy.
    """

    @abstractmethod
    def decide(
        self,
        context: DecisionContext,
    ) -> Decision:
        """
        Produce an immutable Decision from the supplied
        DecisionContext.

        Parameters
        ----------
        context:
            Immutable decision context.

        Returns
        -------
        Decision
            Final decision generated by the strategy.
        """
        ...


__all__ = [
    "BaseDecisionStrategy",
]

# ---------------------------------------------------------------------
# Estado:
# APROBADO
#
# Congelado:
# SÍ
#
# Versión:
# 1.0.0
# ---------------------------------------------------------------------
