"""
Space AI 2.0

Confidence

Immutable confidence value object used by the
Predictor Engine.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(
    frozen=True,
    slots=True,
)
class Confidence:
    """
    Immutable confidence value.

    Represents the confidence assigned to a prediction
    generated by a prediction strategy.

    The value is expected to be normalized in the
    [0.0, 1.0] interval.
    """

    value: float


__all__ = [
    "Confidence",
]

# ---------------------------------------------------------------------
# Estado:
# TERMINADO
#
# Congelado:
# SÍ
#
# Versión:
# 1.0.0
# ---------------------------------------------------------------------
