"""
Space AI 2.0

Predictor Engine

Main prediction engine responsible for orchestrating
prediction strategies.
"""

from __future__ import annotations

from feature_engine.models.feature_vector import FeatureVector
from predictor.prediction_result import PredictionResult
from predictor.strategies.strategy_type import StrategyType
from predictor.strategy_factory import StrategyFactory
from state_engine.models.classification_result import (
    ClassificationResult,
)
from state_engine.state_history import StateHistory


class PredictorEngine:
    """
    Main prediction engine.

    This engine orchestrates prediction strategies
    without depending on any concrete implementation.

    Strategy creation is delegated to a StrategyFactory.
    """

    def __init__(
        self,
        strategy_factory: type[StrategyFactory] = StrategyFactory,
    ) -> None:
        """
        Initialize the Predictor Engine.

        Parameters
        ----------
        strategy_factory:
            Factory responsible for creating prediction
            strategies.
        """

        self._strategy_factory = strategy_factory

    def predict(
        self,
        strategy_type: StrategyType,
        feature_vector: FeatureVector,
        classification: ClassificationResult,
        history: StateHistory,
    ) -> PredictionResult:
        """
        Predict the next system state.

        Parameters
        ----------
        strategy_type:
            Prediction strategy to execute.

        feature_vector:
            Current feature vector.

        classification:
            Current state classification.

        history:
            Historical state evolution.

        Returns
        -------
        PredictionResult
            Prediction generated by the selected strategy.
        """

        strategy = self._strategy_factory.create(
            strategy_type,
        )

        return strategy.predict(
            feature_vector=feature_vector,
            classification=classification,
            history=history,
        )


__all__ = [
    "PredictorEngine",
]

# ---------------------------------------------------------------------
# Estado:
# TERMINADO
#
# Congelado:
# SÍ
#
# Versión:
# 1.0.0
# ---------------------------------------------------------------------
