"""
Space AI 2.0

Decision Context

Immutable Value Object containing all information required
by the Decision Engine to produce a Decision.

The DecisionContext is the single input consumed by every
Decision Strategy implementation.

Compatible with:
    - Python 3.13.5
    - Ruff
    - MyPy (strict)
"""

from __future__ import annotations

# ============================================================================
# Standard Library
# ============================================================================
from dataclasses import dataclass

# ============================================================================
# Space AI - Other Engines
# ============================================================================
from predictor.prediction import Prediction


@dataclass(
    frozen=True,
    slots=True,
)
class DecisionContext:
    """
    Immutable input supplied to the Decision Engine.

    Attributes
    ----------
    prediction:
        Prediction generated by the Predictor Engine.
    """

    prediction: Prediction


__all__ = [
    "DecisionContext",
]

# ---------------------------------------------------------------------
# Estado:
# APROBADO
#
# Congelado:
# SÍ
#
# Versión:
# 1.0.0
# ---------------------------------------------------------------------
