"""
Space AI 2.0

Decision

Immutable decision produced by the Decision Engine.

A Decision represents the final trading action generated
from a DecisionContext after evaluating the configured
decision strategy.

Compatible with:
    - Python 3.13.5
    - Ruff
    - MyPy (strict)
"""

from __future__ import annotations

# ============================================================================
# Standard Library
# ============================================================================
from dataclasses import dataclass

# ============================================================================
# Space AI - Other Engines
# ============================================================================
from ia.core.value_objects import Confidence

# ============================================================================
# Space AI - Same Package
# ============================================================================
from .enums import DecisionAction


@dataclass(
    frozen=True,
    slots=True,
)
class Decision:
    """
    Immutable decision generated by the Decision Engine.

    Attributes
    ----------
    action:
        Final action recommended by the Decision Engine.

    confidence:
        Confidence associated with the decision.

    reason:
        Human-readable explanation describing why the
        decision was generated.
    """

    action: DecisionAction

    confidence: Confidence

    reason: str


__all__ = [
    "Decision",
]

# ---------------------------------------------------------------------
# Estado:
# APROBADO
#
# Congelado:
# SÍ
#
# Versión:
# 1.0.0
# ---------------------------------------------------------------------
