"""
Space AI 2.0

Base Prediction Strategy

Abstract contract implemented by every prediction strategy.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from feature_engine.models.feature_vector import FeatureVector
from predictor.prediction_result import PredictionResult
from state_engine.models.classification_result import ClassificationResult
from state_engine.state_history import StateHistory


class BaseStrategy(ABC):
    """
    Base contract for every prediction strategy.

    A prediction strategy receives the current feature vector,
    the current state classification and the historical state
    evolution to infer the next most probable system state.
    """

    @abstractmethod
    def predict(
        self,
        feature_vector: FeatureVector,
        classification: ClassificationResult,
        history: StateHistory,
    ) -> PredictionResult:
        """
        Predict the next system state.

        Parameters
        ----------
        feature_vector:
            Current extracted feature vector.

        classification:
            Current classification generated by the StateEngine.

        history:
            Historical state evolution.

        Returns
        -------
        PredictionResult
            Prediction generated by the strategy.
        """
        raise NotImplementedError


__all__ = [
    "BaseStrategy",
]

# ---------------------------------------------------------------------
# Estado:
# TERMINADO
#
# Congelado:
# SÍ
#
# Versión:
# 1.1.0
# ---------------------------------------------------------------------
