"""
Space AI 2.0

Bayesian Prediction Strategy

Prediction strategy prepared for Bayesian inference.
"""

from __future__ import annotations

from feature_engine.models.feature_vector import FeatureVector
from predictor.confidence import Confidence
from predictor.prediction import Prediction
from predictor.prediction_result import PredictionResult
from predictor.probability import Probability
from predictor.strategies.base_strategy import BaseStrategy
from state_engine.models.classification_result import (
    ClassificationResult,
)
from state_engine.state_history import StateHistory


class BayesianStrategy(BaseStrategy):
    """
    Prediction strategy prepared for Bayesian inference.

    This initial implementation uses the current
    state classification as the prior prediction.

    Future versions will replace this behavior with
    a complete Bayesian inference model without
    changing the public contract.
    """

    def predict(
        self,
        feature_vector: FeatureVector,
        classification: ClassificationResult,
        history: StateHistory,
    ) -> PredictionResult:
        """
        Predict the next state.

        Parameters
        ----------
        feature_vector:
            Current feature vector.

        classification:
            Current classification generated by the
            StateEngine.

        history:
            Historical state evolution.

        Returns
        -------
        PredictionResult
            Prediction generated by the strategy.
        """

        _ = feature_vector
        _ = history

        prediction = Prediction(
            labels=classification.labels,
            probability=Probability(
                value=classification.confidence,
            ),
            confidence=Confidence(
                value=classification.confidence,
            ),
        )

        return PredictionResult(
            prediction=prediction,
        )


__all__ = [
    "BayesianStrategy",
]

# ---------------------------------------------------------------------
# Estado:
# TERMINADO
#
# Congelado:
# SÍ
#
# Versión:
# 1.0.0
# ---------------------------------------------------------------------
