"""
Space AI 2.0

Markov Prediction Strategy

Prediction strategy based on first-order
Markov chains.
"""

from __future__ import annotations

from feature_engine.models.feature_vector import FeatureVector
from predictor.confidence import Confidence
from predictor.debug.markov_debug_printer import (
    MarkovDebugPrinter,
)
from predictor.models.markov_state_extractor import (
    MarkovStateExtractor,
)
from predictor.models.transition_matrix_builder import (
    TransitionMatrixBuilder,
)
from predictor.prediction import Prediction
from predictor.prediction_result import PredictionResult
from predictor.prediction_status import PredictionStatus
from predictor.strategies.base_strategy import BaseStrategy
from state_engine.models.classification_result import (
    ClassificationResult,
)
from state_engine.state_history import StateHistory


class MarkovStrategy(BaseStrategy):
    """
    Prediction strategy based on a first-order
    Markov chain.

    The strategy infers the most probable next
    state using the transition matrix generated
    from the historical state evolution.
    """

    def predict(
        self,
        feature_vector: FeatureVector,
        classification: ClassificationResult,
        history: StateHistory,
    ) -> PredictionResult:
        """
        Predict the next state using a first-order
        Markov chain.

        Parameters
        ----------
        feature_vector:
            Current feature vector.

        classification:
            Current state classification.

        history:
            Historical state evolution.

        Returns
        -------
        PredictionResult
            Prediction generated by the strategy.
        """

        #
        # Reserved for future strategies.
        #
        _ = feature_vector
        _ = classification

        if history.is_empty():
            raise ValueError(
                "Cannot perform prediction with an empty state history.",
            )

        matrix = TransitionMatrixBuilder.build(
            history,
        )

        current_state = history.last()

        if current_state is None:
            raise ValueError(
                "Unable to determine current state.",
            )

        current_markov_state = MarkovStateExtractor.extract(
            current_state,
        )

        transition = matrix.most_probable(
            current_markov_state,
        )

        if transition is None:
            return PredictionResult(
                status=PredictionStatus.WARMUP,
                reason=("Current state has no outgoing " "Markov transitions."),
            )

        prediction = Prediction(
            labels=transition.target.labels,
            probability=transition.probability,
            confidence=Confidence(
                value=transition.probability.value,
            ),
        )

        MarkovDebugPrinter.print_prediction(
            current_state=current_markov_state,
            transition=transition,
            status=PredictionStatus.READY,
        )

        return PredictionResult(
            status=PredictionStatus.READY,
            prediction=prediction,
        )


__all__ = [
    "MarkovStrategy",
]

# ---------------------------------------------------------------------
# Estado:
# TERMINADO
#
# Congelado:
# NO
#
# Versión:
# 2.0.0
# ---------------------------------------------------------------------
